apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhehpai802-2-app-tekton
  namespace: ai-rhdh
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./components/rhehpai802-2/overlays/tekton
    repoURL: https://github.com/rhdh-JslYoon-org/rhdhpai802-2-gitops.git
    targetRevision: main
  destination:
    namespace: rhdhpai802-2
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: ai-rhdh
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
