apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: rhehpai802-2
  janus-idp.io/tekton: rhehpai802-2
  backstage.io/kubernetes-id: rhehpai802-2
  backstage.io/kubernetes-namespace: rhdhpai802-2
  app.kubernetes.io/part-of: rhehpai802-2
resources:
  - application-dev.yaml