apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: rhehpai802-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhehpai802-2
  name: rhehpai802-2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
